// Site content and data for Photo Gallery - Occasions

export const siteContent = {
  meta: {
    title: 'Photo Gallery - Occasions',
    description: 'Award-winning photography capturing life\'s most meaningful moments — from intimate weddings to milestone celebrations. Every occasion becomes a timeless story.',
    keywords: 'wedding photography, event photography, birthday photography, professional photographer, celebration photography',
  },
  
  hero: {
    badge: 'Award-Winning Photography',
    headline: 'Every occasion becomes a timeless story',
    subtext: 'From the first look to the final dance, from intimate birthdays to grand celebrations — I capture the moments that matter most, so you can relive them forever.',
    ctaPrimary: 'View my work →',
    ctaSecondary: 'Hire me',
    heroImage: 'https://images.unsplash.com/photo-1606800052052-a08af7148866?auto=format&fit=crop&w=1600&q=80',
  },

  portfolio: {
    headline: 'Moments worth preserving',
    subtext: 'Browse my work by occasion — each gallery tells a unique story.',
    categories: [
      { id: 'all', label: 'All' },
      { id: 'wedding', label: 'Weddings' },
      { id: 'birthday', label: 'Birthdays' },
      { id: 'event', label: 'Events' },
    ],
    galleries: [
      {
        id: 1,
        category: 'wedding',
        title: 'Emma & James',
        date: 'May 2024',
        image: 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=800&q=80',
        aspectRatio: '2/3',
      },
      {
        id: 2,
        category: 'birthday',
        title: "Sofia's 30th",
        date: 'March 2024',
        image: 'https://images.unsplash.com/photo-1530103862676-de8c9debad1d?auto=format&fit=crop&w=800&q=80',
        aspectRatio: '4/5',
      },
      {
        id: 3,
        category: 'event',
        title: 'Tech Summit Gala',
        date: 'January 2024',
        image: 'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?auto=format&fit=crop&w=800&q=80',
        aspectRatio: '16/9',
      },
      {
        id: 4,
        category: 'wedding',
        title: 'Priya & Michael',
        date: 'April 2024',
        image: 'https://images.unsplash.com/photo-1591604466107-ec97de577aff?auto=format&fit=crop&w=800&q=80',
        aspectRatio: '1/1',
      },
      {
        id: 5,
        category: 'wedding',
        title: 'Sarah & Tom',
        date: 'June 2024',
        image: 'https://images.unsplash.com/photo-1465495976277-4387d4b0b4c6?auto=format&fit=crop&w=800&q=80',
        aspectRatio: '4/5',
      },
      {
        id: 6,
        category: 'birthday',
        title: 'Little Oliver Turns 1',
        date: 'February 2024',
        image: 'https://images.unsplash.com/photo-1558636508-e0db3814bd1d?auto=format&fit=crop&w=800&q=80',
        aspectRatio: '2/3',
      },
      {
        id: 7,
        category: 'event',
        title: 'Annual Charity Ball',
        date: 'December 2023',
        image: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=800&q=80',
        aspectRatio: '16/9',
      },
      {
        id: 8,
        category: 'wedding',
        title: 'David & Lucas',
        date: 'March 2024',
        image: 'https://images.unsplash.com/photo-1522673607200-164d1b6ce486?auto=format&fit=crop&w=800&q=80',
        aspectRatio: '4/5',
      },
      {
        id: 9,
        category: 'birthday',
        title: "Grandma Rose's 90th",
        date: 'May 2024',
        image: 'https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?auto=format&fit=crop&w=800&q=80',
        aspectRatio: '1/1',
      },
      {
        id: 10,
        category: 'event',
        title: 'Corporate Retreat 2024',
        date: 'February 2024',
        image: 'https://images.unsplash.com/photo-1505236858219-8359eb29e329?auto=format&fit=crop&w=800&q=80',
        aspectRatio: '16/9',
      },
      {
        id: 11,
        category: 'wedding',
        title: 'Aisha & Ryan',
        date: 'July 2024',
        image: 'https://images.unsplash.com/photo-1583939003579-730e3918a45a?auto=format&fit=crop&w=800&q=80',
        aspectRatio: '2/3',
      },
      {
        id: 12,
        category: 'birthday',
        title: "Marcus' Sweet 16",
        date: 'April 2024',
        image: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&w=800&q=80',
        aspectRatio: '4/5',
      },
      {
        id: 13,
        category: 'event',
        title: 'Art Gallery Opening',
        date: 'March 2024',
        image: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=800&q=80',
        aspectRatio: '1/1',
      },
      {
        id: 14,
        category: 'wedding',
        title: 'Hannah & Chris',
        date: 'August 2024',
        image: 'https://images.unsplash.com/photo-1566933293069-b55c7f326dd4?auto=format&fit=crop&w=800&q=80',
        aspectRatio: '2/3',
      },
      {
        id: 15,
        category: 'birthday',
        title: "Twins' 5th Birthday Bash",
        date: 'June 2024',
        image: 'https://images.unsplash.com/photo-1555324734-eb5e5c65fae7?auto=format&fit=crop&w=800&q=80',
        aspectRatio: '16/9',
      },
    ],
  },

  about: {
    eyebrow: 'About the photographer',
    headline: 'I believe every celebration deserves to be remembered beautifully',
    paragraphs: [
      "For over eight years, I've had the privilege of documenting life's most meaningful moments — from intimate vows exchanged at sunrise to milestone birthdays surrounded by generations of family. My approach is simple: stay present, stay unobtrusive, and capture the emotion as it unfolds.",
      "I'm not interested in stiff poses or forced smiles. I'm drawn to the in-between moments — the tearful hug, the spontaneous laughter, the quiet glance across the room. Those are the images you'll treasure decades from now.",
      "Based in San Francisco, I work with clients locally and travel for destination celebrations. Whether it's your wedding day or your grandmother's 90th birthday, I'm here to make sure the story is told with care, artistry, and heart.",
    ],
    cta: "Let's work together →",
    portraitImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=800&q=80',
  },

  services: {
    headline: 'Photography packages designed for your occasion',
    subtext: "Every celebration is unique. Choose the package that fits your needs, or let's create something custom.",
    packages: [
      {
        id: 1,
        name: 'Essentials',
        price: '$1,200',
        duration: '4 hours',
        description: 'Perfect for intimate gatherings, small birthdays, and engagement sessions.',
        features: [
          'Up to 4 hours of coverage',
          '200+ edited high-resolution images',
          'Online gallery with download',
          'Print release included',
          '2-week turnaround',
        ],
        highlighted: false,
      },
      {
        id: 2,
        name: 'Premium',
        price: '$2,800',
        duration: '8 hours',
        description: 'The most popular choice for weddings and large milestone celebrations.',
        features: [
          'Full 8 hours of coverage',
          '500+ edited high-resolution images',
          'Second photographer included',
          'Online gallery + USB drive',
          'Print release + 20 prints',
          '3-week turnaround',
          'Complimentary engagement session',
        ],
        highlighted: true,
      },
      {
        id: 3,
        name: 'Luxury',
        price: '$4,500',
        duration: '12 hours',
        description: 'For multi-day events, destination weddings, and full-service coverage.',
        features: [
          'Up to 12 hours of coverage',
          '800+ edited high-resolution images',
          'Two photographers + assistant',
          'Custom leather-bound album (40 pages)',
          'Online gallery + USB + cloud backup',
          'Print release + 50 fine art prints',
          '4-week turnaround',
          'Engagement + day-after session',
          'Priority booking for future events',
        ],
        highlighted: false,
      },
    ],
  },

  testimonials: {
    headline: 'What clients are saying',
    subtext: 'Real stories from real celebrations — here's what it's like working with me.',
    quotes: [
      {
        id: 1,
        text: "We couldn't be happier with our wedding photos. Every image tells a story, and looking through them brings us right back to that perfect day. Truly a treasure.",
        author: 'Emma & James',
        occasion: 'Wedding, May 2024',
        avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=150&q=80',
      },
      {
        id: 2,
        text: "My 30th birthday felt like a movie premiere thanks to these stunning photos. So much laughter, joy, and love captured in every frame. I'll cherish these forever.",
        author: 'Sofia Martinez',
        occasion: 'Birthday, March 2024',
        avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=150&q=80',
      },
      {
        id: 3,
        text: 'Professional, unobtrusive, and incredibly talented. Our corporate gala photos exceeded expectations — they captured the energy and elegance perfectly.',
        author: 'David Chen',
        occasion: 'Corporate Event, January 2024',
        avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=150&q=80',
      },
      {
        id: 4,
        text: 'Our multicultural wedding was beautifully documented with such sensitivity and artistry. Every tradition, every emotion — captured perfectly.',
        author: 'Priya & Michael',
        occasion: 'Wedding, April 2024',
        avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80',
      },
      {
        id: 5,
        text: "From our son's first birthday to our grandmother's 90th — this photographer has become part of our family story. The quality and care are unmatched.",
        author: 'The Rodriguez Family',
        occasion: 'Multiple Events',
        avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80',
      },
      {
        id: 6,
        text: 'Absolutely worth every penny. The engagement session made us so comfortable, and the wedding day felt effortless. The photos are pure magic.',
        author: 'Sarah & Tom',
        occasion: 'Wedding, June 2024',
        avatar: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?auto=format&fit=crop&w=150&q=80',
      },
    ],
  },

  contact: {
    headline: "Let's capture your story",
    subtext: 'Tell me about your occasion, and I'll get back to you within 24 hours with availability and a custom quote.',
    form: {
      namePlaceholder: 'John Smith',
      emailPlaceholder: 'john@example.com',
      phonePlaceholder: '+1 (555) 123-4567',
      occasionLabel: 'What type of occasion?',
      occasionOptions: [
        'Wedding',
        'Engagement Session',
        'Birthday Party',
        'Anniversary',
        'Corporate Event',
        'Family Reunion',
        'Graduation',
        'Other Celebration',
      ],
      messagePlaceholder: 'Tell me about your event — the date, location, vision, and any special details you'd like me to know...',
      submitButton: 'Send inquiry',
    },
    whatsapp: {
      text: 'Prefer to chat?',
      number: '+1234567890',
      message: 'Hi! I'd like to inquire about photography for my upcoming event.',
    },
    info: [
      {
        icon: 'Mail',
        label: 'Email',
        value: 'hello@photographer.com',
        link: 'mailto:hello@photographer.com',
      },
      {
        icon: 'MapPin',
        label: 'Location',
        value: 'San Francisco, CA',
        subtext: 'Available for travel worldwide',
      },
      {
        icon: 'Clock',
        label: 'Response Time',
        value: 'Within 24 hours',
        subtext: 'Usually same-day',
      },
    ],
  },

  footer: {
    tagline: 'Capturing life's most meaningful moments',
    social: [
      { platform: 'Instagram', url: 'https://instagram.com', handle: '@photographer' },
      { platform: 'Facebook', url: 'https://facebook.com', handle: 'Photographer' },
      { platform: 'Pinterest', url: 'https://pinterest.com', handle: 'Photographer' },
    ],
    links: [
      { label: 'Portfolio', href: '#portfolio' },
      { label: 'About', href: '#about' },
      { label: 'Services', href: '#services' },
      { label: 'Contact', href: '#contact' },
    ],
    copyright: '© 2024 Photo Gallery - Occasions. All rights reserved.',
  },
};
